name: CI

on:
  # Roda a pipeline quando houver push na branch 'dev'
  push:
    branches: [ "dev" ]

  # Roda a pipeline para PRs que têm como destino a branch 'main'
  pull_request:
    branches: [ "main" ]

  # Permite execução manual
  workflow_dispatch:

jobs:
  etl-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests datetime logging gdown openpyxl pyarrow

    - name: Rodar script ETL
      run: |
        python desafio.py

    - name: Verificar formatação com black
      run: |
        pip install black
        black --check .


